### ISSUE TITLE
Word stem searching

### ISSUE THREAD

**Issue by alis0nc** [Sefaria/Sefaria-Android#11]
I just ran into an issue similar to https://github.com/Sefaria/Sefaria-Project/issues/262 at Genesis 1:8: "וַיִּקְרָ֧א אֱלֹהִ֛ים לָֽרָקִ֖יעַ שָׁמָ֑יִם". I'd expect searching for "רקיע" to come up with that pasuk, but it doesn't. It just returns texts that have "רקיע" as is.

**Comment by nsantacruz** [comment]
We currently have stem searching working on the site and are working on getting this working on the apps also.
